//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int ID { get; set; }
        public Nullable<int> User_id { get; set; }
        public string Fullname { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone_number { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Oder_date { get; set; }
    
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual User User { get; set; }
    }
}
